i-RNA: irna::iRNA_stat::Parser::Parser Class Reference
irna::iRNA_stat::Parser::Parser Class Reference
Public Member Functions
def __init__
Instanciate Parser object.
def sortdict
Sort the dictionnary.
def getData
Search name in input list.
def getUnique
Get unique data.
Detailed Description
Definition at line 10 of file Parser.py.
Constructor & Destructor Documentation
def irna::iRNA_stat::Parser::Parser::__init__ (self)
Instanciate Parser object.
Definition at line 16 of file Parser.py.
Member Function Documentation
def irna::iRNA_stat::Parser::Parser::getData (self, input_list, name)
Search name in input list.
Parameters:
input_list,: List
name,: Search criteria
Definition at line 34 of file Parser.py.
References getUnique().
Referenced by irna::iRNA_stat::Rand_data::Rand_data::getallSofts(), and sortdict().
def irna::iRNA_stat::Parser::Parser::getUnique (self, data_list)
Get unique data.
Parameters:
data_list,: list of data
Definition at line 46 of file Parser.py.
Referenced by irna::iRNA_stat::pValue_selection::pValue_selection::compute_Davidmatrix(), and getData().
def irna::iRNA_stat::Parser::Parser::sortdict (self, dictionnary, criteria)
Sort the dictionnary.
Parameters:
dictionnary,: Dictionnary list
criteria,: Sort criteria
Definition at line 25 of file Parser.py.
References getData().
Referenced by irna::iRNA_stat::pValue_selection::pValue_selection::compute_Davidmatrix(), and irna::iRNA_stat::pValue_selection::pValue_selection::compute_similarity().
The documentation for this class was generated from the following file:
/home/amine/workspace/iRNA/irna/iRNA_stat/Parser.py