i-RNA: irna::David2tulip::Multilist::Multilist Class Reference
irna::David2tulip::Multilist::Multilist Class Reference
Public Member Functions
def __init__
Instanciate multilist object.
def getnodelists
Read nodes.
def getPosTable
def createedges
Create edges.
def setdata
Build the graph.
def getFilter
Parse gene known.
def writefilterlist
Write the filtered multilist.
def GOfilter
Filter mRNA based on GO-known gene.
Public Attributes
multilist_file
filtered
Detailed Description
Definition at line 12 of file Multilist.py.
Constructor & Destructor Documentation
def irna::David2tulip::Multilist::Multilist::__init__ (self, multilist_file)
Instanciate multilist object.
Parameters:
multilist_file,: Multilist file
Definition at line 19 of file Multilist.py.
Member Function Documentation
def irna::David2tulip::Multilist::Multilist::createedges (self, header_nodes, tail_nodes)
Create edges.
Parameters:
header_nodes,: list of header nodes
tail_nodes,: list of tail nodes
Returns:
: list of edges
Definition at line 100 of file Multilist.py.
References irna::David2tulip::Parser::Parser::createnodes(), irna::David2tulip::Parser::Parser::getlinknode(), getnodelists(), getPosTable(), multilist_file, and setdata().
Referenced by getPosTable(), and setdata().
def irna::David2tulip::Multilist::Multilist::getFilter (self, filter_file)
Parse gene known.
Parameters:
filter_file,: GO file
Returns:
: List of mRNA known from the GO
Definition at line 155 of file Multilist.py.
References filtered, multilist_file, and writefilterlist().
Referenced by setdata(), and writefilterlist().
def irna::David2tulip::Multilist::Multilist::getnodelists (self)
Read nodes.
Definition at line 66 of file Multilist.py.
References getPosTable(), and multilist_file.
Referenced by createedges().
def irna::David2tulip::Multilist::Multilist::getPosTable (self, header_nodes, header)
Parameters:
header_nod,:
Definition at line 85 of file Multilist.py.
References createedges(), and multilist_file.
Referenced by createedges(), and getnodelists().
def irna::David2tulip::Multilist::Multilist::GOfilter (self, filter_file, results)
Filter mRNA based on GO-known gene.
Parameters:
filter_file,: GO file
results,: Path to result repertory
Definition at line 198 of file Multilist.py.
Referenced by writefilterlist().
def irna::David2tulip::Multilist::Multilist::setdata (self, node_objects, edge_objects)
Build the graph.
Parameters:
node_objects,: list of node objects
edge_objects,: list of edge objects
Returns:
: List of node and edge objects
Definition at line 136 of file Multilist.py.
References createedges(), and getFilter().
Referenced by createedges().
def irna::David2tulip::Multilist::Multilist::writefilterlist (self, go_list, results)
Write the filtered multilist.
Parameters:
go_list,: List of mRNA known
results,: Path to result repertory
Definition at line 175 of file Multilist.py.
References filtered, getFilter(), GOfilter(), multilist_file, and writefilterlist().
Referenced by getFilter(), and writefilterlist().
Member Data Documentation
irna::David2tulip::Multilist::Multilist::filtered
Definition at line 175 of file Multilist.py.
Referenced by getFilter(), and writefilterlist().
irna::David2tulip::Multilist::Multilist::multilist_file
Definition at line 19 of file Multilist.py.
Referenced by createedges(), getFilter(), getnodelists(), getPosTable(), and writefilterlist().
The documentation for this class was generated from the following file:
/home/amine/workspace/iRNA/irna/David2tulip/Multilist.py