i-RNA: irna::iRNA_pred::Stat::Stat Class Reference
irna::iRNA_pred::Stat::Stat Class Reference
Public Member Functions
def __init__
Stat constructor.
def ComputeGC
def GetGC
Get the GC percentage.
def GetLenSeq
Get the mean length of sequence.
def SeqInf
Write Seq Inf data.
def openSeqInf
Open seq_inf file and write header.
def CloseSeqInf
Close the Seq Inf file.
Public Attributes
file
Static Public Attributes
tuple seqlen = len(seq)
Detailed Description
Definition at line 9 of file Stat.py.
Constructor & Destructor Documentation
def irna::iRNA_pred::Stat::Stat::__init__ (self)
Stat constructor.
Reimplemented in irna::iRNA_pred::Fasta::Fasta.
Definition at line 15 of file Stat.py.
Member Function Documentation
def irna::iRNA_pred::Stat::Stat::CloseSeqInf (self)
Close the Seq Inf file.
Definition at line 79 of file Stat.py.
Referenced by openSeqInf().
def irna::iRNA_pred::Stat::Stat::ComputeGC (self, name, seq)
Definition at line 18 of file Stat.py.
def irna::iRNA_pred::Stat::Stat::GetGC (self)
Get the GC percentage.
Returns:
: The GC percentage
Definition at line 44 of file Stat.py.
References GetLenSeq(), irna::iRNA_pred::RanRNA::RanRNA::NbSeq, and SeqInf().
def irna::iRNA_pred::Stat::Stat::GetLenSeq (self)
Get the mean length of sequence.
Returns:
: Mean length
Definition at line 52 of file Stat.py.
References openSeqInf().
Referenced by GetGC().
def irna::iRNA_pred::Stat::Stat::openSeqInf (self)
Open seq_inf file and write header.
Definition at line 67 of file Stat.py.
References CloseSeqInf().
Referenced by irna::iRNA_pred::Fasta::Fasta::ExtractFasta(), and GetLenSeq().
def irna::iRNA_pred::Stat::Stat::SeqInf (self, name, seqlen)
Write Seq Inf data.
Definition at line 59 of file Stat.py.
References file.
Referenced by GetGC().
Member Data Documentation
irna::iRNA_pred::Stat::Stat::file
Definition at line 67 of file Stat.py.
Referenced by SeqInf().
tuple irna::iRNA_pred::Stat::Stat::seqlen = len(seq) [static]
Compute the length and the number of GC
@param name: Name of the sequence
@param seq: RNA sequence
Definition at line 26 of file Stat.py.
The documentation for this class was generated from the following file:
/home/amine/workspace/iRNA/irna/iRNA_pred/Stat.py