i-RNA: irna::iRNA_stat::Soft::Soft Class Reference
irna::iRNA_stat::Soft::Soft Class Reference
Public Member Functions
def __init__
Instanciate soft object.
def getSoftinf
def getSoftnum
def __cmp__
General method to compare node based on the name.
Public Attributes
id
type_sol
score_type
Detailed Description
Definition at line 10 of file Soft.py.
Constructor & Destructor Documentation
def irna::iRNA_stat::Soft::Soft::__init__ (self, soft_file)
Instanciate soft object.
Definition at line 17 of file Soft.py.
References getSoftinf().
Member Function Documentation
def irna::iRNA_stat::Soft::Soft::__cmp__ (self, other)
General method to compare node based on the name.
Parameters:
other,: Compared value
Definition at line 57 of file Soft.py.
Referenced by getSoftnum().
def irna::iRNA_stat::Soft::Soft::getSoftinf (self, soft_file)
Parameters:
soft_file,:
Definition at line 25 of file Soft.py.
Referenced by __init__().
def irna::iRNA_stat::Soft::Soft::getSoftnum (self, name)
Parameters:
name,:
Definition at line 45 of file Soft.py.
References __cmp__(), and id.
Member Data Documentation
irna::iRNA_stat::Soft::Soft::id
Definition at line 25 of file Soft.py.
Referenced by getSoftnum().
irna::iRNA_stat::Soft::Soft::score_type
Definition at line 25 of file Soft.py.
irna::iRNA_stat::Soft::Soft::type_sol
Definition at line 25 of file Soft.py.
The documentation for this class was generated from the following file:
/home/amine/workspace/iRNA/irna/iRNA_stat/Soft.py