i-RNA: irna::David2tulip::Parser::Parser Class Reference
irna::David2tulip::Parser::Parser Class Reference
Public Member Functions
def __init__
Instanciate Parser object.
def createnodes
Create the list of nodes.
def addelements
Add an element in list of objects.
def getlinknode
Get a node based on its name.
def getlinkedge
def getsRNA
Get list of sRNA.
def getTarget
Get targets of one sRNA if category.
def loadObject
Load object.
def printObject
Write object.
Detailed Description
Definition at line 11 of file Parser.py.
Constructor & Destructor Documentation
def irna::David2tulip::Parser::Parser::__init__ (self)
Instanciate Parser object.
Definition at line 17 of file Parser.py.
Member Function Documentation
def irna::David2tulip::Parser::Parser::addelements (self, list_objects, element)
Add an element in list of objects.
Parameters:
list_objects,: list of objects
element,: object
Definition at line 44 of file Parser.py.
References getlinknode().
Referenced by createnodes(), and irna::David2tulip::Similarity::Similarity::setdata().
def irna::David2tulip::Parser::Parser::createnodes (self, list_element, gender, number)
Create the list of nodes.
Parameters:
list_element,:
gender,: Gender of the list
Returns:
: list of nodes
Definition at line 27 of file Parser.py.
References addelements().
Referenced by irna::David2tulip::Multilist::Multilist::createedges().
def irna::David2tulip::Parser::Parser::getlinkedge (self, edge_objects, sRNA, mRNA)
Parameters:
edge_objects,: List of edge objects
sRNA,: sRNA
mRNA,: mRNA
Definition at line 68 of file Parser.py.
References getsRNA(), and getTarget().
Referenced by getlinknode(), irna::David2tulip::Interact::Interact::setdata(), irna::David2tulip::pValue::pValue::setdata(), and irna::David2tulip::David::David::writefile().
def irna::David2tulip::Parser::Parser::getlinknode (self, node_objects, name)
Get a node based on its name.
Parameters:
node_objects,: List of node objects
name,: Name of searched object
Returns:
: node
Definition at line 55 of file Parser.py.
References getlinkedge().
Referenced by addelements(), irna::David2tulip::Multilist::Multilist::createedges(), irna::David2tulip::Similarity::Similarity::setdata(), and irna::David2tulip::Name::Name::setdata().
def irna::David2tulip::Parser::Parser::getsRNA (self, node_objects)
Get list of sRNA.
Parameters:
node_objects,: List of node objects
Returns:
: List of sRNA
Definition at line 82 of file Parser.py.
References loadObject().
Referenced by irna::David2tulip::David::David::analysis(), and getlinkedge().
def irna::David2tulip::Parser::Parser::getTarget (self, sRNA, edge_objects)
Get targets of one sRNA if category.
Parameters:
sRNA,: sRNA name
edge_objects,: List of edge objects
Definition at line 91 of file Parser.py.
Referenced by irna::David2tulip::David::David::analysis(), and getlinkedge().
def irna::David2tulip::Parser::Parser::loadObject (self, pickledump)
Load object.
Parameters:
pickledump,: Filename
Returns:
: Object loaded
Definition at line 100 of file Parser.py.
References printObject().
Referenced by getsRNA().
def irna::David2tulip::Parser::Parser::printObject (self, obj, pickledump)
Write object.
Parameters:
obj,: Object to dump
pickledump,: Filename
Definition at line 117 of file Parser.py.
Referenced by loadObject(), and irna::David2tulip::David::David::parseChart().
The documentation for this class was generated from the following file:
/home/amine/workspace/iRNA/irna/David2tulip/Parser.py