i-RNA: irna::iRNA_pred::Merger::Merger Class Reference
irna::iRNA_pred::Merger::Merger Class Reference
Merge the xml files in a sqlite database.
Public Member Functions
def __init__
Initiate the constructor.
def buildTree
Read the xml tree and copy the data into the sqlite database.
def getData
Parse xml tree.
def setRNA
Parse RNA_inf file.
def merge
Merge mycarn xml files into a sqlite database.
Public Attributes
repIn
files
softprevious
Static Public Attributes
tuple result_data = etree.Element("result")
Detailed Description
Merge the xml files in a sqlite database.
Definition at line 14 of file Merger.py.
Constructor & Destructor Documentation
def irna::iRNA_pred::Merger::Merger::__init__ (self, repIn)
Initiate the constructor.
Parameters:
repIn,: Result repertory
Definition at line 23 of file Merger.py.
Member Function Documentation
def irna::iRNA_pred::Merger::Merger::buildTree (self, tree, dbmanage)
Read the xml tree and copy the data into the sqlite database.
Parameters:
tree,: xml tree parsed
dbmanage,: Database manager
Definition at line 38 of file Merger.py.
References getData(), and softprevious.
Referenced by merge().
def irna::iRNA_pred::Merger::Merger::getData (self, file)
Parse xml tree.
Parameters:
file,: Result part in Xml format
Returns:
: resulting tree
Definition at line 71 of file Merger.py.
References setRNA().
Referenced by buildTree(), irna::iRNA_stat::Rand_data::Rand_data::getallSofts(), and merge().
def irna::iRNA_pred::Merger::Merger::merge (self, dbmanage)
Merge mycarn xml files into a sqlite database.
Parameters:
dbmanage,: Database manager
Definition at line 101 of file Merger.py.
References buildTree(), getData(), and repIn.
Referenced by setRNA().
def irna::iRNA_pred::Merger::Merger::setRNA (self, dbmanage, RNA_inf, type)
Parse RNA_inf file.
Parameters:
RNA_inf,: Path to RNA_inf file
dbmanage,: Access to the database
type,: Type of RNA
Definition at line 87 of file Merger.py.
References files, and merge().
Referenced by getData().
Member Data Documentation
irna::iRNA_pred::Merger::Merger::files
Definition at line 23 of file Merger.py.
Referenced by setRNA().
irna::iRNA_pred::Merger::Merger::repIn
Definition at line 23 of file Merger.py.
Referenced by merge().
tuple irna::iRNA_pred::Merger::Merger::result_data = etree.Element("result") [static]
Definition at line 16 of file Merger.py.
irna::iRNA_pred::Merger::Merger::softprevious
Definition at line 23 of file Merger.py.
Referenced by buildTree().
The documentation for this class was generated from the following file:
/home/amine/workspace/iRNA/irna/iRNA_pred/Merger.py