i-RNA: irna::iRNA_pred::Interaction::Interaction Class Reference
irna::iRNA_pred::Interaction::Interaction Class Reference
: Store information on interaction.
Public Member Functions
def __init__
Init Interaction object.
def setSoft
Set software node.
def getlastmRNA
Get mRNA attribute.
def getlastsRNA
Get sRNA attribute.
def addListOfComparison
Add a list of comparison node.
def addComparison
Add a comparison node.
def getLastchildnode
def setScoreList
Set ListOfComparison score.
def getResult
def println
Print object data.
def setMatrix
Manage matrix load and format.
def formatMatrix
Format into integer the matrix.
def loadMatrix
Load the matrix of score.
def getPosition
Get the position on matrix.
def scoreSequence
Score two sequences.
Public Attributes
root
schema_root
Static Public Attributes
matrix = None
Detailed Description
: Store information on interaction.
Definition at line 14 of file Interaction.py.
Constructor & Destructor Documentation
def irna::iRNA_pred::Interaction::Interaction::__init__ (self)
Init Interaction object.
Definition at line 21 of file Interaction.py.
Member Function Documentation
def irna::iRNA_pred::Interaction::Interaction::addComparison (self, data)
Add a comparison node.
Parameters:
data,: Comparison result
Definition at line 65 of file Interaction.py.
References getLastchildnode(), schema_root, and setScoreList().
Referenced by getlastsRNA().
def irna::iRNA_pred::Interaction::Interaction::addListOfComparison (self, mRNA, sRNA)
Add a list of comparison node.
Parameters:
mRNA,: mRNA id
sRNA,: sRNA id
Definition at line 57 of file Interaction.py.
References getLastchildnode().
Referenced by getlastmRNA().
def irna::iRNA_pred::Interaction::Interaction::formatMatrix (self, mat)
Format into integer the matrix.
Parameters:
mat,: Matrix data in string format
Returns:
: Matrix in integer format
Definition at line 118 of file Interaction.py.
Referenced by println().
def irna::iRNA_pred::Interaction::Interaction::getLastchildnode (self)
Returns:
: The last child from root
Definition at line 73 of file Interaction.py.
References getResult(), and root.
Referenced by addComparison(), addListOfComparison(), getlastmRNA(), and setSoft().
def irna::iRNA_pred::Interaction::Interaction::getlastmRNA (self)
Get mRNA attribute.
Returns:
: Value of mRNA attribute
Definition at line 38 of file Interaction.py.
References addListOfComparison(), getLastchildnode(), and schema_root.
def irna::iRNA_pred::Interaction::Interaction::getlastsRNA (self)
Get sRNA attribute.
Returns:
: Value of sRNA attribute
Definition at line 47 of file Interaction.py.
References addComparison().
Referenced by setSoft().
def irna::iRNA_pred::Interaction::Interaction::getPosition (self, letter)
Get the position on matrix.
Parameters:
letter,: One letter in the sequence
Returns:
: The position on matrix
Definition at line 158 of file Interaction.py.
References getPosition(), and matrix.
Referenced by getPosition(), and loadMatrix().
def irna::iRNA_pred::Interaction::Interaction::getResult (self)
Returns:
: The tree in text format
Definition at line 88 of file Interaction.py.
References loadMatrix(), and setMatrix().
Referenced by getLastchildnode().
def irna::iRNA_pred::Interaction::Interaction::loadMatrix (self, matrix)
Load the matrix of score.
Parameters:
matrix,: Matrix file
Returns:
: Matrix of score
Definition at line 133 of file Interaction.py.
References getPosition(), matrix, and scoreSequence().
Referenced by getResult(), and setMatrix().
def irna::iRNA_pred::Interaction::Interaction::println (self)
Print object data.
Definition at line 96 of file Interaction.py.
References formatMatrix(), and matrix.
Referenced by setScoreList().
def irna::iRNA_pred::Interaction::Interaction::scoreSequence (self, seqs)
Score two sequences.
Parameters:
seqs,: Table of two sequences
Returns:
: The score of the alignement
Definition at line 175 of file Interaction.py.
Referenced by loadMatrix().
def irna::iRNA_pred::Interaction::Interaction::setMatrix (self, matrix)
Manage matrix load and format.
Parameters:
matrix,: Matrix file
Definition at line 105 of file Interaction.py.
References loadMatrix().
Referenced by getResult().
def irna::iRNA_pred::Interaction::Interaction::setScoreList (self, score)
Set ListOfComparison score.
Parameters:
score,: Score the whole comparison
Definition at line 81 of file Interaction.py.
References println(), and schema_root.
Referenced by addComparison().
def irna::iRNA_pred::Interaction::Interaction::setSoft (self, soft_name, ref)
Set software node.
Parameters:
soft_name,: Software name
ref,: Software num
Definition at line 30 of file Interaction.py.
References getLastchildnode(), getlastsRNA(), and schema_root.
Member Data Documentation
irna::iRNA_pred::Interaction::Interaction::matrix = None [static]
Definition at line 15 of file Interaction.py.
Referenced by getPosition(), loadMatrix(), and println().
irna::iRNA_pred::Interaction::Interaction::root
Definition at line 21 of file Interaction.py.
Referenced by getLastchildnode().
irna::iRNA_pred::Interaction::Interaction::schema_root
Definition at line 30 of file Interaction.py.
Referenced by addComparison(), getlastmRNA(), setScoreList(), and setSoft().
The documentation for this class was generated from the following file:
/home/amine/workspace/iRNA/irna/iRNA_pred/Interaction.py