i-RNA: irna::iRNA_seq::Sequences::Sequences Class Reference
irna::iRNA_seq::Sequences::Sequences Class Reference
Public Member Functions
def __init__
Instanciate Sequence object.
def parse
Get parsed data.
def invers_compl
Inverse and complemente gene sequence.
def fractionalGene
Get Gene between indicated set of position.
def completeGene
Get the complete Gene.
def setGeneFunction
Define the getGene function to use.
def setdefaultmRNAlen
Compute default mRNA length.
def writemRNA
Write mRNA multifasta file.
def writesRNA
Write sRNA multifasta file.
def writeCorresponding
Write corresponding geneID to genename for mRNA.
Public Attributes
organism
list_genes
DNA
Detailed Description
Definition at line 9 of file Sequences.py.
Constructor & Destructor Documentation
def irna::iRNA_seq::Sequences::Sequences::__init__ (self)
Instanciate Sequence object.
Definition at line 15 of file Sequences.py.
Member Function Documentation
def irna::iRNA_seq::Sequences::Sequences::completeGene (self, genedict, begin = None, end = None)
Get the complete Gene.
Parameters:
genedict,: list of Gene dictionnary
Returns:
: Complete gene sequence
Definition at line 63 of file Sequences.py.
References completeGene(), fractionalGene(), and setdefaultmRNAlen().
Referenced by completeGene(), invers_compl(), and writemRNA().
def irna::iRNA_seq::Sequences::Sequences::fractionalGene (self, genedict, begin, end)
Get Gene between indicated set of position.
Parameters:
genedict,: list of Gene dictionnary
Returns:
: Fractionnal gene sequence
Definition at line 54 of file Sequences.py.
References DNA, and setGeneFunction().
Referenced by completeGene(), and invers_compl().
def irna::iRNA_seq::Sequences::Sequences::invers_compl (self, gene)
Inverse and complemente gene sequence.
Parameters:
gene,: Gene sequence
Definition at line 33 of file Sequences.py.
References completeGene(), DNA, and fractionalGene().
Referenced by parse(), and writemRNA().
def irna::iRNA_seq::Sequences::Sequences::parse (self, obj)
Get parsed data.
Parameters:
obj,: Data object
Definition at line 25 of file Sequences.py.
References invers_compl().
def irna::iRNA_seq::Sequences::Sequences::setdefaultmRNAlen (self, begin, end, complete)
Compute default mRNA length.
Parameters:
begin,: sRNA begin
end,: sRNA end
complete,: Complete flag
Returns:
: RNA length
Definition at line 84 of file Sequences.py.
References list_genes, organism, setdefaultmRNAlen(), setGeneFunction(), and writemRNA().
Referenced by completeGene(), and setdefaultmRNAlen().
def irna::iRNA_seq::Sequences::Sequences::setGeneFunction (self, complete)
Define the getGene function to use.
Parameters:
complete,: Complete flag
Returns:
: Function pointer
Definition at line 72 of file Sequences.py.
Referenced by fractionalGene(), and setdefaultmRNAlen().
def irna::iRNA_seq::Sequences::Sequences::writeCorresponding (self, results)
Write corresponding geneID to genename for mRNA.
Definition at line 162 of file Sequences.py.
Referenced by writesRNA().
def irna::iRNA_seq::Sequences::Sequences::writemRNA (self, begin, end, results, complete)
Write mRNA multifasta file.
Parameters:
begin,: sRNA begin
end,: sRNA end
results,: Path to result repertory
complete,: Complete flag
Definition at line 101 of file Sequences.py.
References completeGene(), invers_compl(), organism, and writesRNA().
Referenced by setdefaultmRNAlen().
def irna::iRNA_seq::Sequences::Sequences::writesRNA (self, results, srna_data)
Write sRNA multifasta file.
Parameters:
results,: Path to result repertory
srna_data,: sRNA list
Definition at line 133 of file Sequences.py.
References list_genes, organism, and writeCorresponding().
Referenced by writemRNA().
Member Data Documentation
irna::iRNA_seq::Sequences::Sequences::DNA
Definition at line 15 of file Sequences.py.
Referenced by fractionalGene(), and invers_compl().
irna::iRNA_seq::Sequences::Sequences::list_genes
Definition at line 15 of file Sequences.py.
Referenced by setdefaultmRNAlen(), and writesRNA().
irna::iRNA_seq::Sequences::Sequences::organism
Definition at line 15 of file Sequences.py.
Referenced by setdefaultmRNAlen(), writemRNA(), and writesRNA().
The documentation for this class was generated from the following file:
/home/amine/workspace/iRNA/irna/iRNA_seq/Sequences.py