i-RNA: irna::iRNA_pred::Parse::Parse Class Reference
irna::iRNA_pred::Parse::Parse Class Reference
: Parse data from the different software.
Public Member Functions
def parseGuugle
Parse Guugle result.
def parseIntaRNA
Parse IntaRNA result.
def parseRNAup
Parse RNAup result.
def parseRNAplex
Parse RNAplex and RNAduplex result.
def parseRNAduplex
Parse RNAplex and RNAduplex result.
def getposition_RNAcofold0
Get the position of interaction for RNAcofold.
def getposition_RNAcofold1
Get the position of interaction for RNAcofold.
def reverseElongate
Get a double reverse for a tab of tab.
def forwardTable
Reverse a table.
def parseRNAcofold
Parse RNAcofold result.
def getResultSequence_RNAhybrid
Get contact sequence.
def parseRNAhybrid
Parse RNAhybrid result.
def getPositions_rip
Get the positions for rip problem output.
def elongatePositions_rip
Elongate the contact position.
def getSequences_53
Get the sequence in contact in 5'3' sense.
def getSequences_local_reversed
Get the sequence in contact in 5'3' sense.
def consensus
Find the contact position between sRNA and mRNA.
def reverseSequence
Reverse a sequence.
def reverseTablemax
Reverse a table.
def reverseMinTable
Reverse a table into 5'3'.
def parseRactip
Parse Ractip result.
def readCompfile
Read the comp_list file.
def comparaison
Determine if comparison is needed.
def parseBlastall
Parse Blastall result.
def parseBistaRNA
Parse BistaRNA result.
def parseYass
Parse Yass output.
def parseSsearch
Parse ssearch output.
def parsePairfold
Parse Pairfold result.
def runParsing
Run the parsing.
Detailed Description
: Parse data from the different software.
Definition at line 14 of file Parse.py.
Member Function Documentation
def irna::iRNA_pred::Parse::Parse::comparaison (self, mRNA, sRNA, comp_data)
Determine if comparison is needed.
Parameters:
mRNA,: mRNA name
sRNA,: sRNA name
comp_data,: Comparison data
Returns:
: True if comparison is expected, False otherwise
Definition at line 705 of file Parse.py.
References comparaison().
Referenced by comparaison(), parseRactip(), and parseYass().
def irna::iRNA_pred::Parse::Parse::consensus (self, resultsRNA, resultmRNA, tab_sRNA, tab_mRNA, debutsRNA, debutmRNA, i, j)
Find the contact position between sRNA and mRNA.
Parameters:
resultsRNA,: New table of contact for sRNA
resultmRNA,: New table of contact for mRNA
tab_sRNA,: Old table of contact for sRNA
tab_mRNA,: Old table of contact for mRNA
debutsRNA,: sRNA begin
debutmRNA,: mRNA begin
i,: Position in the old table of sRNA
j,: Position in the old table of mRNA
Definition at line 511 of file Parse.py.
References consensus(), reverseMinTable(), reverseSequence(), and reverseTablemax().
Referenced by consensus(), getSequences_53(), parseBistaRNA(), parseRactip(), parseRNAcofold(), parseRNAhybrid(), and parseSsearch().
def irna::iRNA_pred::Parse::Parse::elongatePositions_rip (self, tab)
Elongate the contact position.
Parameters:
tab,: Table of contact position
Returns:
: Table elongate
Definition at line 452 of file Parse.py.
References getSequences_53(), and getSequences_local_reversed().
Referenced by parseBistaRNA(), parseRactip(), parseRNAcofold(), parseRNAhybrid(), and parseSsearch().
def irna::iRNA_pred::Parse::Parse::forwardTable (self, tab_RNA)
Reverse a table.
Parameters:
tab_RNA,: Table of RNA
Returns:
: Reversed table
Definition at line 269 of file Parse.py.
Referenced by getposition_RNAcofold1(), parseRNAcofold(), and parseSsearch().
def irna::iRNA_pred::Parse::Parse::getposition_RNAcofold0 (self, result)
Get the position of interaction for RNAcofold.
Parameters:
result,: sRNA result
Returns:
: tabmRNA, tabsRNA
Definition at line 219 of file Parse.py.
References getposition_RNAcofold1().
Referenced by parseRNAcofold(), parseRNAduplex(), and parseSsearch().
def irna::iRNA_pred::Parse::Parse::getposition_RNAcofold1 (self, result)
Get the position of interaction for RNAcofold.
Parameters:
result,: mRNA result
Returns:
: tabmRNA, tabsRNA
Definition at line 235 of file Parse.py.
References forwardTable(), and reverseElongate().
Referenced by getposition_RNAcofold0(), parseRNAcofold(), and parseSsearch().
def irna::iRNA_pred::Parse::Parse::getPositions_rip (self, RNA_r, seq)
Get the positions for rip problem output.
Parameters:
RNA_r,: RNA result output
Returns:
: Position of contact for RNA
Definition at line 438 of file Parse.py.
Referenced by parseBistaRNA(), parseRactip(), and parseRNAhybrid().
def irna::iRNA_pred::Parse::Parse::getResultSequence_RNAhybrid (self, out_RNA, in_RNA, RNA_begin, length_RNA, int_char)
Get contact sequence.
Parameters:
out_RNA,: Non contact nucleotid
in_RNA,: Contact nucleotid
RNA_begin,: Begining position of the RNA
length_RNA,: Length of the RNA sequence
int_char,: Interaction caracter
Definition at line 339 of file Parse.py.
References parseRNAhybrid().
Referenced by parseRNAcofold(), and parseRNAhybrid().
def irna::iRNA_pred::Parse::Parse::getSequences_53 (self, RNA, tab_RNA)
Get the sequence in contact in 5'3' sense.
Parameters:
RNA,: RNA sequence
tab_RNA,: Position of contact for RNA
Returns:
: RNA tab of contact sequences
Definition at line 477 of file Parse.py.
References consensus(), and reverseSequence().
Referenced by elongatePositions_rip(), parseBistaRNA(), and parseRactip().
def irna::iRNA_pred::Parse::Parse::getSequences_local_reversed (self, RNA)
Get the sequence in contact in 5'3' sense.
Parameters:
RNA,: RNA sequence
Returns:
: RNA tab of contact sequences
Definition at line 491 of file Parse.py.
Referenced by elongatePositions_rip().
def irna::iRNA_pred::Parse::Parse::parseBistaRNA (self, data, matrix, root)
Parse BistaRNA result.
Parameters:
data,: Soft result
matrix,: score matrix
root,: xml root node
Definition at line 766 of file Parse.py.
References consensus(), elongatePositions_rip(), getPositions_rip(), getSequences_53(), parseSsearch(), and parseYass().
Referenced by parseBlastall(), and runParsing().
def irna::iRNA_pred::Parse::Parse::parseBlastall (self, data, matrix, root, complist_file)
Parse Blastall result.
Parameters:
data,: Soft result
matrix,: score matrix
root,: xml root node
complist_file,: Comparison list file
Definition at line 721 of file Parse.py.
References parseBistaRNA().
Referenced by readCompfile(), and runParsing().
def irna::iRNA_pred::Parse::Parse::parseGuugle (self, data, matrix, root)
Parse Guugle result.
Parameters:
data,: result
matrix,: score matrix
root,: xml root node
Definition at line 22 of file Parse.py.
References parseIntaRNA().
Referenced by parsePairfold().
def irna::iRNA_pred::Parse::Parse::parseIntaRNA (self, data, matrix, root)
Parse IntaRNA result.
Parameters:
data,: Soft result
matrix,: score matrix
root,: xml root node
Definition at line 109 of file Parse.py.
References parseRNAup().
Referenced by parseGuugle(), and parsePairfold().
def irna::iRNA_pred::Parse::Parse::parsePairfold (self, data, matrix, root)
Parse Pairfold result.
Parameters:
data,: Soft result
matrix,: score matrix
root,: xml root node
Definition at line 892 of file Parse.py.
References parseGuugle(), parseIntaRNA(), parseRNAcofold(), parseRNAduplex(), parseRNAplex(), parseRNAup(), reverseTablemax(), and runParsing().
Referenced by parseSsearch(), and runParsing().
def irna::iRNA_pred::Parse::Parse::parseRactip (self, data, matrix, root)
Parse Ractip result.
Parameters:
data,: Soft result
matrix,: score matrix
root,: xml root node
Definition at line 619 of file Parse.py.
References comparaison(), consensus(), elongatePositions_rip(), getPositions_rip(), getSequences_53(), readCompfile(), reverseSequence(), and reverseTablemax().
Referenced by reverseSequence(), and runParsing().
def irna::iRNA_pred::Parse::Parse::parseRNAcofold (self, data, matrix, root)
Parse RNAcofold result.
Parameters:
data,: Soft result
matrix,: score matrix
root,: xml root node
Definition at line 283 of file Parse.py.
References consensus(), elongatePositions_rip(), forwardTable(), getposition_RNAcofold0(), getposition_RNAcofold1(), getResultSequence_RNAhybrid(), reverseElongate(), and reverseTablemax().
Referenced by parsePairfold(), and reverseElongate().
def irna::iRNA_pred::Parse::Parse::parseRNAduplex (self, data, matrix, root)
Parse RNAplex and RNAduplex result.
Parameters:
data,: Soft result
matrix,: score matrix
root,: xml root node
Definition at line 200 of file Parse.py.
References getposition_RNAcofold0().
Referenced by parsePairfold(), and parseRNAplex().
def irna::iRNA_pred::Parse::Parse::parseRNAhybrid (self, data, matrix, root)
Parse RNAhybrid result.
Parameters:
data,: Soft result
matrix,: score matrix
root,: xml root node
Definition at line 365 of file Parse.py.
References consensus(), elongatePositions_rip(), getPositions_rip(), getResultSequence_RNAhybrid(), and reverseTablemax().
Referenced by getResultSequence_RNAhybrid(), and runParsing().
def irna::iRNA_pred::Parse::Parse::parseRNAplex (self, data, matrix, root)
Parse RNAplex and RNAduplex result.
Parameters:
data,: Soft result
matrix,: score matrix
root,: xml root node
Definition at line 180 of file Parse.py.
References parseRNAduplex().
Referenced by parsePairfold(), and parseRNAup().
def irna::iRNA_pred::Parse::Parse::parseRNAup (self, data, matrix, root)
Parse RNAup result.
Parameters:
data,: Soft result
matrix,: score matrix
root,: xml root node
Definition at line 152 of file Parse.py.
References parseRNAplex().
Referenced by parseIntaRNA(), and parsePairfold().
def irna::iRNA_pred::Parse::Parse::parseSsearch (self, data, sRNA, matrix, root, complist_file)
Parse ssearch output.
Parameters:
data,: Soft result
sRNA,: sRNA name
matrix,: score matrix
root,: xml root node
complist_file,: Comparison list file
Definition at line 851 of file Parse.py.
References consensus(), elongatePositions_rip(), forwardTable(), getposition_RNAcofold0(), getposition_RNAcofold1(), parsePairfold(), and reverseElongate().
Referenced by parseBistaRNA(), and runParsing().
def irna::iRNA_pred::Parse::Parse::parseYass (self, data, matrix, root, complist_file)
Parse Yass output.
Parameters:
data,: Soft result
matrix,: score matrix
root,: xml root node
complist_file,: Comparison list file
Definition at line 826 of file Parse.py.
References comparaison(), and readCompfile().
Referenced by parseBistaRNA(), and runParsing().
def irna::iRNA_pred::Parse::Parse::readCompfile (self, complist_file)
Read the comp_list file.
Parameters:
complist_file,: Comparison list file
Returns:
: Comparison data
Definition at line 678 of file Parse.py.
References parseBlastall(), and readCompfile().
Referenced by parseRactip(), parseYass(), and readCompfile().
def irna::iRNA_pred::Parse::Parse::reverseElongate (self, tab)
Get a double reverse for a tab of tab.
Parameters:
tab,: Table of table
Returns:
: Reversed table of table
Definition at line 255 of file Parse.py.
References parseRNAcofold().
Referenced by getposition_RNAcofold1(), parseRNAcofold(), and parseSsearch().
def irna::iRNA_pred::Parse::Parse::reverseMinTable (self, tab_RNA)
Reverse a table into 5'3'.
Parameters:
tab_RNA,: Table of RNA
Returns:
: Reversed table
Definition at line 605 of file Parse.py.
Referenced by consensus().
def irna::iRNA_pred::Parse::Parse::reverseSequence (self, seq)
Reverse a sequence.
Parameters:
seq,: Sequence of text
Returns:
: Reversed sequence
Definition at line 582 of file Parse.py.
References parseRactip().
Referenced by consensus(), getSequences_53(), and parseRactip().
def irna::iRNA_pred::Parse::Parse::reverseTablemax (self, tab_RNA, maxValue)
Reverse a table.
Parameters:
tab_RNA,: Table of RNA
Returns:
: Reversed table
Definition at line 593 of file Parse.py.
Referenced by consensus(), parsePairfold(), parseRactip(), parseRNAcofold(), and parseRNAhybrid().
def irna::iRNA_pred::Parse::Parse::runParsing (self, soft_name, matrix, complist_file, sRNA, mRNA, data, root)
Run the parsing.
Parameters:
cmd,: Soft command
complist_file,: Comparison list file
data,: Soft result
Definition at line 935 of file Parse.py.
References parseBistaRNA(), parseBlastall(), parsePairfold(), parseRactip(), parseRNAhybrid(), parseSsearch(), and parseYass().
Referenced by parsePairfold().
The documentation for this class was generated from the following file:
/home/amine/workspace/iRNA/irna/iRNA_pred/Parse.py