i-RNA: irna::David2tulip::Sqlite_manager::Sqlite_manager Class Reference
irna::David2tulip::Sqlite_manager::Sqlite_manager Class Reference
: Handle database connection, disconnection and querying.
Public Member Functions
def __init__
Instanciate Sqlite_manager object.
def createSQLdb
Create the database.
def connectDB
Connect to the database.
def disconnectDB
Disconnect the database.
def disconnectDB2
Disconnect the database and copy on to the disk.
def setSoft
Insert soft name.
def setRNA
Insert RNA.
def setInteract
Insert interaction.
def commitRetry
Retry the commit operation.
def setContact
Insert contacts.
def getSoft
Get if software exist by its id.
def getSoftname
Get if software exist by its id.
def getidSoftsbyname
Get id of softwares corresponding to one name.
def getallRNAlength
Get all RNA length.
def getallRNA
Get all RNA name from one type.
def getRNA
Get an RNA by its name and type.
def getsRNAlenbyIntid
Get an sRNA length from an interaction.
def getAllsRNAlenbyIntid
Get an sRNA length from an interaction.
def getsRNAidbyIntid
Get an sRNAid from an interaction.
def getAllsRNAidbyIntid
Get an sRNAid from an interaction.
def getmRNAlenbyIntid
Get an mRNA from an interaction.
def getAllmRNAlenbyIntid
Get an mRNA from an interaction.
def getNbInteract
Count the number of interaction for one software.
def getInteract
Get interactions of one software.
def getScore
Get the score of an interaction.
def getAllScore
Get the score for several interactions.
def getAllSoft
Get all the software.
def getsRNAbyIntid
Get the name of an sRNA from interaction key.
def getmRNAbyIntid
Get the name of an mRNA from interaction key.
def listit
Convert fetchall result into list of list.
def listscore
Unlist score.
def getPositionsbyIntid
Get position for one interaction.
def getallsRNA
Get all sRNA.
def getallsRNAname
Get an sRNA name and unlist.
def getIntbysRNAid
Get the interactid for an sRNA.
def IndexInteractidOnContact
Create index on interactid for contact.
def IndexSrnaidOnInteract
Create index on srnaid for interact.
def IndexMrnaidOnInteract
Create index on mrnaid for interact.
def createIndexes
Create index for most use connection.
Public Attributes
db_path
db_file
fastmode
conn2
conn
cur
Detailed Description
: Handle database connection, disconnection and querying.
Definition at line 16 of file Sqlite_manager.py.
Constructor & Destructor Documentation
def irna::David2tulip::Sqlite_manager::Sqlite_manager::__init__ (self, result, db_file, fastmode)
Instanciate Sqlite_manager object.
Parameters:
result,: Path where to write the database
db_file,: SQlite db file
fastmode,: fastmode flag
Definition at line 25 of file Sqlite_manager.py.
Member Function Documentation
def irna::David2tulip::Sqlite_manager::Sqlite_manager::commitRetry (self)
Retry the commit operation.
Returns:
: State of the commit
Definition at line 154 of file Sqlite_manager.py.
Referenced by irna::iRNA_stat::Sqlite_manager::Sqlite_manager::setContact(), setContact(), irna::iRNA_pred::Sqlite_manager::Sqlite_manager::setContact(), irna::iRNA_stat::Sqlite_manager::Sqlite_manager::setInteract(), setInteract(), irna::iRNA_stat::Sqlite_manager::Sqlite_manager::setRNA(), setRNA(), irna::iRNA_pred::Sqlite_manager::Sqlite_manager::setRNA(), irna::iRNA_stat::Sqlite_manager::Sqlite_manager::setSoft(), irna::iRNA_pred::Sqlite_manager::Sqlite_manager::setSoft(), and setSoft().
def irna::David2tulip::Sqlite_manager::Sqlite_manager::connectDB (self)
Connect to the database.
Definition at line 48 of file Sqlite_manager.py.
Referenced by createSQLdb().
def irna::David2tulip::Sqlite_manager::Sqlite_manager::createIndexes (self)
Create index for most use connection.
Definition at line 531 of file Sqlite_manager.py.
Referenced by getallsRNAname().
def irna::David2tulip::Sqlite_manager::Sqlite_manager::createSQLdb (self)
Create the database.
Definition at line 34 of file Sqlite_manager.py.
References conn2, connectDB(), db_file, and db_path.
def irna::David2tulip::Sqlite_manager::Sqlite_manager::disconnectDB (self)
Disconnect the database.
Definition at line 63 of file Sqlite_manager.py.
References conn, conn2, disconnectDB2(), irna::David2tulip::Files::Files::fastmode, and fastmode.
def irna::David2tulip::Sqlite_manager::Sqlite_manager::disconnectDB2 (self)
Disconnect the database and copy on to the disk.
Definition at line 74 of file Sqlite_manager.py.
References cur, and setSoft().
Referenced by disconnectDB().
def irna::David2tulip::Sqlite_manager::Sqlite_manager::getAllmRNAlenbyIntid (self, table_interactid)
Get an mRNA from an interaction.
Parameters:
table_interactid,: table of interaction id
Returns:
: List of mRNA length
Definition at line 341 of file Sqlite_manager.py.
References getScore().
Referenced by getAllsRNAidbyIntid().
def irna::David2tulip::Sqlite_manager::Sqlite_manager::getallRNA (self, type_RNA)
Get all RNA name from one type.
Parameters:
type_RNA,: Type of RNA
Returns:
: list of RNA
Definition at line 240 of file Sqlite_manager.py.
References getsRNAlenbyIntid().
Referenced by getidSoftsbyname().
def irna::David2tulip::Sqlite_manager::Sqlite_manager::getallRNAlength (self, type_RNA)
Get all RNA length.
Parameters:
type_RNA,: Type of RNA
Returns:
: list of RNA with their length
Definition at line 228 of file Sqlite_manager.py.
References getRNA().
Referenced by getSoftname().
def irna::David2tulip::Sqlite_manager::Sqlite_manager::getAllScore (self, table_interactid)
Get the score for several interactions.
Parameters:
table_interactid,: list of interaction key
Returns:
: List of score
Definition at line 395 of file Sqlite_manager.py.
References getmRNAbyIntid(), and listit().
Referenced by getNbInteract().
def irna::David2tulip::Sqlite_manager::Sqlite_manager::getAllSoft (self)
Get all the software.
Returns:
: List of software
Definition at line 409 of file Sqlite_manager.py.
References listit(), and listscore().
Referenced by getInteract().
def irna::David2tulip::Sqlite_manager::Sqlite_manager::getallsRNA (self)
Get all sRNA.
Returns:
: List of rnaid
Definition at line 474 of file Sqlite_manager.py.
References IndexMrnaidOnInteract().
Referenced by getmRNAbyIntid().
def irna::David2tulip::Sqlite_manager::Sqlite_manager::getAllsRNAidbyIntid (self, table_interactid)
Get an sRNAid from an interaction.
Parameters:
interactid,: Interaction id
Returns:
: List of sRNAid
Definition at line 310 of file Sqlite_manager.py.
References getAllmRNAlenbyIntid(), and getmRNAbyIntid().
Referenced by getAllsRNAlenbyIntid().
def irna::David2tulip::Sqlite_manager::Sqlite_manager::getAllsRNAlenbyIntid (self, table_interactid)
Get an sRNA length from an interaction.
Parameters:
table_interactid,: table of interaction id
Returns:
: list of sRNA length
Definition at line 280 of file Sqlite_manager.py.
References getAllsRNAidbyIntid().
Referenced by getRNA().
def irna::David2tulip::Sqlite_manager::Sqlite_manager::getallsRNAname (self)
Get an sRNA name and unlist.
Returns:
: List of rnaid
Definition at line 485 of file Sqlite_manager.py.
References createIndexes(), IndexInteractidOnContact(), IndexMrnaidOnInteract(), and IndexSrnaidOnInteract().
Referenced by listit().
def irna::David2tulip::Sqlite_manager::Sqlite_manager::getidSoftsbyname (self, name)
Get id of softwares corresponding to one name.
Parameters:
name,: name of a software
Returns:
: list of softid
Definition at line 216 of file Sqlite_manager.py.
References getallRNA().
Referenced by getSoft().
def irna::David2tulip::Sqlite_manager::Sqlite_manager::getIntbysRNAid (self, srnaid)
Get the interactid for an sRNA.
Parameters:
srnaid,: rna key
Returns:
: List of interactid
Definition at line 497 of file Sqlite_manager.py.
Referenced by listscore().
def irna::David2tulip::Sqlite_manager::Sqlite_manager::getInteract (self, softid)
Get interactions of one software.
Parameters:
softid,: soft key
Returns:
: List of interactid
Definition at line 371 of file Sqlite_manager.py.
References getAllSoft(), and listscore().
Referenced by getmRNAlenbyIntid().
def irna::David2tulip::Sqlite_manager::Sqlite_manager::getmRNAbyIntid (self, interactid)
Get the name of an mRNA from interaction key.
Parameters:
interactid,: interaction key
Returns:
: name of the mRNA
Definition at line 433 of file Sqlite_manager.py.
References getallsRNA().
Referenced by getAllScore(), irna::iRNA_stat::Sqlite_manager::Sqlite_manager::getAllsRNAidbyIntid(), irna::iRNA_pred::Sqlite_manager::Sqlite_manager::getAllsRNAidbyIntid(), and getAllsRNAidbyIntid().
def irna::David2tulip::Sqlite_manager::Sqlite_manager::getmRNAlenbyIntid (self, interactid)
Get an mRNA from an interaction.
Parameters:
interactid,: Interaction id
Returns:
: mRNA length
Definition at line 327 of file Sqlite_manager.py.
References getInteract(), and getNbInteract().
Referenced by getsRNAidbyIntid().
def irna::David2tulip::Sqlite_manager::Sqlite_manager::getNbInteract (self, softid)
Count the number of interaction for one software.
Parameters:
softid,: soft key
Returns:
: Number of interaction
Definition at line 358 of file Sqlite_manager.py.
References getAllScore(), and listscore().
Referenced by getmRNAlenbyIntid().
def irna::David2tulip::Sqlite_manager::Sqlite_manager::getPositionsbyIntid (self, interactid)
Get position for one interaction.
Parameters:
interactid,: interact key
Returns:
: List of position
Definition at line 463 of file Sqlite_manager.py.
References IndexInteractidOnContact(), and IndexSrnaidOnInteract().
Referenced by getsRNAbyIntid().
def irna::David2tulip::Sqlite_manager::Sqlite_manager::getRNA (self, name, type_RNA)
Get an RNA by its name and type.
Parameters:
name,: RNA name
type,: RNA type
Returns:
: A rnaid
Definition at line 254 of file Sqlite_manager.py.
References getAllsRNAlenbyIntid().
Referenced by getallRNAlength().
def irna::David2tulip::Sqlite_manager::Sqlite_manager::getScore (self, interactid)
Get the score of an interaction.
Parameters:
interactid,: interaction key
Returns:
: List of score
Definition at line 383 of file Sqlite_manager.py.
References getsRNAbyIntid().
Referenced by getAllmRNAlenbyIntid().
def irna::David2tulip::Sqlite_manager::Sqlite_manager::getSoft (self, softid)
Get if software exist by its id.
Parameters:
softid,: Soft key
Returns:
: A softid
Definition at line 192 of file Sqlite_manager.py.
References getidSoftsbyname().
Referenced by setContact().
def irna::David2tulip::Sqlite_manager::Sqlite_manager::getSoftname (self, softid)
Get if software exist by its id.
Parameters:
softid,: Soft key
Returns:
: A software name
Definition at line 204 of file Sqlite_manager.py.
References getallRNAlength(), and listscore().
Referenced by setContact().
def irna::David2tulip::Sqlite_manager::Sqlite_manager::getsRNAbyIntid (self, interactid)
Get the name of an sRNA from interaction key.
Parameters:
interactid,: interaction key
Returns:
: name of the sRNA
Definition at line 421 of file Sqlite_manager.py.
References getPositionsbyIntid().
Referenced by getScore(), irna::iRNA_stat::Sqlite_manager::Sqlite_manager::getsRNAlenbyIntid(), irna::iRNA_pred::Sqlite_manager::Sqlite_manager::getsRNAlenbyIntid(), and getsRNAlenbyIntid().
def irna::David2tulip::Sqlite_manager::Sqlite_manager::getsRNAidbyIntid (self, interactid)
Get an sRNAid from an interaction.
Parameters:
interactid,: Interaction id
Definition at line 296 of file Sqlite_manager.py.
References getmRNAlenbyIntid().
Referenced by getsRNAlenbyIntid().
def irna::David2tulip::Sqlite_manager::Sqlite_manager::getsRNAlenbyIntid (self, interactid)
Get an sRNA length from an interaction.
Parameters:
interactid,: Interaction id
Returns:
: sRNA length
Definition at line 266 of file Sqlite_manager.py.
References getsRNAbyIntid(), and getsRNAidbyIntid().
Referenced by getallRNA().
def irna::David2tulip::Sqlite_manager::Sqlite_manager::IndexInteractidOnContact (self)
Create index on interactid for contact.
Definition at line 507 of file Sqlite_manager.py.
Referenced by irna::iRNA_stat::Sqlite_manager::Sqlite_manager::getallsRNAname(), getallsRNAname(), irna::iRNA_pred::Sqlite_manager::Sqlite_manager::getallsRNAname(), and getPositionsbyIntid().
def irna::David2tulip::Sqlite_manager::Sqlite_manager::IndexMrnaidOnInteract (self)
Create index on mrnaid for interact.
Definition at line 523 of file Sqlite_manager.py.
Referenced by getallsRNA(), irna::iRNA_stat::Sqlite_manager::Sqlite_manager::getallsRNAname(), irna::iRNA_pred::Sqlite_manager::Sqlite_manager::getallsRNAname(), and getallsRNAname().
def irna::David2tulip::Sqlite_manager::Sqlite_manager::IndexSrnaidOnInteract (self)
Create index on srnaid for interact.
Definition at line 515 of file Sqlite_manager.py.
Referenced by irna::iRNA_stat::Sqlite_manager::Sqlite_manager::getallsRNAname(), getallsRNAname(), irna::iRNA_pred::Sqlite_manager::Sqlite_manager::getallsRNAname(), and getPositionsbyIntid().
def irna::David2tulip::Sqlite_manager::Sqlite_manager::listit (self, t)
Convert fetchall result into list of list.
Returns:
: List of list
Definition at line 444 of file Sqlite_manager.py.
References getallsRNAname().
Referenced by getAllScore(), irna::iRNA_stat::Sqlite_manager::Sqlite_manager::getAllSoft(), irna::iRNA_pred::Sqlite_manager::Sqlite_manager::getAllSoft(), and getAllSoft().
def irna::David2tulip::Sqlite_manager::Sqlite_manager::listscore (self, score)
Unlist score.
Returns:
: List of score
Definition at line 452 of file Sqlite_manager.py.
References getIntbysRNAid(), and listscore().
Referenced by getAllSoft(), irna::iRNA_stat::Sqlite_manager::Sqlite_manager::getInteract(), getInteract(), irna::iRNA_pred::Sqlite_manager::Sqlite_manager::getInteract(), irna::iRNA_stat::Sqlite_manager::Sqlite_manager::getNbInteract(), getNbInteract(), irna::iRNA_pred::Sqlite_manager::Sqlite_manager::getNbInteract(), irna::iRNA_stat::Sqlite_manager::Sqlite_manager::getSoftname(), getSoftname(), irna::iRNA_pred::Sqlite_manager::Sqlite_manager::getSoftname(), irna::iRNA_stat::Sqlite_manager::Sqlite_manager::listscore(), listscore(), and irna::iRNA_pred::Sqlite_manager::Sqlite_manager::listscore().
def irna::David2tulip::Sqlite_manager::Sqlite_manager::setContact (self, interactid, tab)
Insert contacts.
Parameters:
interactid,: Interaction key
tab,: Table of contact
Definition at line 169 of file Sqlite_manager.py.
References commitRetry(), getSoft(), and getSoftname().
Referenced by setInteract().
def irna::David2tulip::Sqlite_manager::Sqlite_manager::setInteract (self, sRNAid, mRNAid, softid)
Insert interaction.
Parameters:
sRNAid,: sRNA key
mRNAid,: mRNA key
softid,: soft key
Returns:
: Last insert id
Definition at line 137 of file Sqlite_manager.py.
References commitRetry(), and setContact().
Referenced by setRNA().
def irna::David2tulip::Sqlite_manager::Sqlite_manager::setRNA (self, RNAtab)
Insert RNA.
Parameters:
RNAtab,: Table of RNA
Definition at line 107 of file Sqlite_manager.py.
References commitRetry(), cur, and setInteract().
Referenced by setSoft().
def irna::David2tulip::Sqlite_manager::Sqlite_manager::setSoft (self, name)
Insert soft name.
Parameters:
name,: Soft name
Returns:
: Last insert id
Definition at line 90 of file Sqlite_manager.py.
References commitRetry(), and setRNA().
Referenced by disconnectDB2().
Member Data Documentation
irna::David2tulip::Sqlite_manager::Sqlite_manager::conn
Definition at line 48 of file Sqlite_manager.py.
Referenced by irna::iRNA_stat::Sqlite_manager::Sqlite_manager::disconnectDB(), disconnectDB(), and irna::iRNA_pred::Sqlite_manager::Sqlite_manager::disconnectDB().
irna::David2tulip::Sqlite_manager::Sqlite_manager::conn2
Definition at line 48 of file Sqlite_manager.py.
Referenced by irna::iRNA_stat::Sqlite_manager::Sqlite_manager::createSQLdb(), createSQLdb(), irna::iRNA_pred::Sqlite_manager::Sqlite_manager::createSQLdb(), irna::iRNA_stat::Sqlite_manager::Sqlite_manager::disconnectDB(), disconnectDB(), and irna::iRNA_pred::Sqlite_manager::Sqlite_manager::disconnectDB().
irna::David2tulip::Sqlite_manager::Sqlite_manager::cur
Definition at line 48 of file Sqlite_manager.py.
Referenced by irna::iRNA_stat::Sqlite_manager::Sqlite_manager::disconnectDB2(), disconnectDB2(), irna::iRNA_pred::Sqlite_manager::Sqlite_manager::disconnectDB2(), irna::iRNA_stat::Sqlite_manager::Sqlite_manager::setRNA(), setRNA(), and irna::iRNA_pred::Sqlite_manager::Sqlite_manager::setRNA().
irna::David2tulip::Sqlite_manager::Sqlite_manager::db_file
Definition at line 25 of file Sqlite_manager.py.
Referenced by irna::iRNA_stat::Sqlite_manager::Sqlite_manager::createSQLdb(), createSQLdb(), and irna::iRNA_pred::Sqlite_manager::Sqlite_manager::createSQLdb().
irna::David2tulip::Sqlite_manager::Sqlite_manager::db_path
Definition at line 25 of file Sqlite_manager.py.
Referenced by irna::iRNA_stat::Sqlite_manager::Sqlite_manager::createSQLdb(), createSQLdb(), and irna::iRNA_pred::Sqlite_manager::Sqlite_manager::createSQLdb().
irna::David2tulip::Sqlite_manager::Sqlite_manager::fastmode
Definition at line 25 of file Sqlite_manager.py.
Referenced by irna::iRNA_stat::Sqlite_manager::Sqlite_manager::disconnectDB(), irna::iRNA_pred::Sqlite_manager::Sqlite_manager::disconnectDB(), disconnectDB(), irna::iRNA_stat::Files::Files::getfiles(), and irna::iRNA_pred::Files::Files::getfiles().
The documentation for this class was generated from the following file:
/home/amine/workspace/iRNA/irna/David2tulip/Sqlite_manager.py