i-RNA: irna::iRNA_pred::Comparison::Comparaison Class Reference
irna::iRNA_pred::Comparison::Comparaison Class Reference
: Create coupled files and the list of comparison
Public Member Functions
def __init__
The constructor.
def runCommand
Run command.
def createCouple
Create the couple.
def createRNAcofoldCouple
Create the couple for RNAcofold.
def getCouple
Get a couple in sRNA repertory.
def getRNAcofoldCouple
Get a couple in sRNA repertory.
def getName
Get the name of the fasta file.
def getCommand
Build the command.
def getFastaFiles
Get the list of data.
def getUnique
Get unique data.
def getComparison
Define the comparison.
def runComparison
Run a comparison.
def manageCouple
Manage the creation of couples.
def prepareComparaison
Control Mpi procedure.
Public Attributes
comp_list
sRNA_out
mRNA_out
soft_path
mf_mRNA
Detailed Description
: Create coupled files and the list of comparison
Definition at line 15 of file Comparison.py.
Constructor & Destructor Documentation
def irna::iRNA_pred::Comparison::Comparaison::__init__ (self, comp_list, sRNA_out, mRNA_out, soft_path, mf_mRNA)
The constructor.
Definition at line 20 of file Comparison.py.
Member Function Documentation
def irna::iRNA_pred::Comparison::Comparaison::createCouple (self, sRNA, mRNA)
Create the couple.
Parameters:
sRNA,: name of the sRNA file
mRNA,: name of the mRNA file
Definition at line 57 of file Comparison.py.
References createRNAcofoldCouple(), mRNA_out, and sRNA_out.
Referenced by manageCouple(), and runCommand().
def irna::iRNA_pred::Comparison::Comparaison::createRNAcofoldCouple (self, sRNA, mRNA)
Create the couple for RNAcofold.
Parameters:
sRNA,: name of the sRNA file
mRNA,: name of the mRNA file
Definition at line 82 of file Comparison.py.
References getCouple(), mRNA_out, and sRNA_out.
Referenced by createCouple(), and manageCouple().
def irna::iRNA_pred::Comparison::Comparaison::getCommand (self, build_command, sRNA, mRNA, RNAcofold_flag)
Build the command.
Parameters:
build_command,: Soft command
sRNA,: name of the sRNA file
mRNA,: name of the mRNA file
RNAcofold_flag,: Flag for RNAcofold special case
Returns:
: Comparison command
Definition at line 158 of file Comparison.py.
References getCouple(), getFastaFiles(), getRNAcofoldCouple(), and getUnique().
Referenced by getComparison(), and getRNAcofoldCouple().
def irna::iRNA_pred::Comparison::Comparaison::getComparison (self, command, RNAcofold_flag)
Define the comparison.
Parameters:
command,: Soft command
RNAcofold_flag,: Flag for RNAcofold special case
Returns:
: Comparison list and the number of comparison
Definition at line 206 of file Comparison.py.
References comp_list, getCommand(), getFastaFiles(), getUnique(), mRNA_out, runComparison(), and sRNA_out.
Referenced by getFastaFiles().
def irna::iRNA_pred::Comparison::Comparaison::getCouple (self, sRNA, mRNA)
Get a couple in sRNA repertory.
Parameters:
sRNA,: name of the sRNA file
mRNA,: name of the mRNA file
Returns:
: Return the file couple
Definition at line 109 of file Comparison.py.
References getRNAcofoldCouple(), and sRNA_out.
Referenced by createRNAcofoldCouple(), and getCommand().
def irna::iRNA_pred::Comparison::Comparaison::getFastaFiles (self, repertory)
Get the list of data.
Parameters:
repertory,: Interest repertory
Returns:
: Return the list of file of interest
Definition at line 183 of file Comparison.py.
References getComparison().
Referenced by getCommand(), getComparison(), and manageCouple().
def irna::iRNA_pred::Comparison::Comparaison::getName (self, regex, fasta_file)
Get the name of the fasta file.
Parameters:
regex,: Regex used to detect the name
fasta_file,: A standard fasta file with her path
Returns:
: The name of the fasta file
Definition at line 141 of file Comparison.py.
References mf_mRNA, mRNA_out, soft_path, and sRNA_out.
Referenced by getRNAcofoldCouple().
def irna::iRNA_pred::Comparison::Comparaison::getRNAcofoldCouple (self, sRNA, mRNA)
Get a couple in sRNA repertory.
Parameters:
sRNA,: name of the sRNA file
mRNA,: name of the mRNA file
Returns:
: Return the file couple
Definition at line 125 of file Comparison.py.
References getCommand(), and getName().
Referenced by getCommand(), and getCouple().
def irna::iRNA_pred::Comparison::Comparaison::getUnique (self, data_list)
Get unique data.
Parameters:
data_list,: list of data
Definition at line 192 of file Comparison.py.
References comp_list.
Referenced by irna::iRNA_stat::pValue_selection::pValue_selection::compute_Davidmatrix(), getCommand(), and getComparison().
def irna::iRNA_pred::Comparison::Comparaison::manageCouple (self)
Manage the creation of couples.
Definition at line 308 of file Comparison.py.
References comp_list, createCouple(), createRNAcofoldCouple(), getFastaFiles(), manageCouple(), mRNA_out, prepareComparaison(), and sRNA_out.
Referenced by manageCouple(), and runComparison().
def irna::iRNA_pred::Comparison::Comparaison::prepareComparaison (self)
Control Mpi procedure.
Definition at line 344 of file Comparison.py.
Referenced by manageCouple().
def irna::iRNA_pred::Comparison::Comparaison::runCommand (self, cmd)
Run command.
Parameters:
cmd,: Command to run
Definition at line 39 of file Comparison.py.
References createCouple(), and sRNA_out.
def irna::iRNA_pred::Comparison::Comparaison::runComparison (self, cmd)
Run a comparison.
Parameters:
cmd,: Soft command
Returns:
: Return soft result
Definition at line 288 of file Comparison.py.
References comp_list, manageCouple(), mRNA_out, and sRNA_out.
Referenced by getComparison().
Member Data Documentation
irna::iRNA_pred::Comparison::Comparaison::comp_list
Definition at line 20 of file Comparison.py.
Referenced by getComparison(), getUnique(), manageCouple(), and runComparison().
irna::iRNA_pred::Comparison::Comparaison::mf_mRNA
Definition at line 20 of file Comparison.py.
Referenced by getName().
irna::iRNA_pred::Comparison::Comparaison::mRNA_out
Definition at line 20 of file Comparison.py.
Referenced by createCouple(), createRNAcofoldCouple(), getComparison(), getName(), manageCouple(), and runComparison().
irna::iRNA_pred::Comparison::Comparaison::soft_path
Definition at line 20 of file Comparison.py.
Referenced by getName().
irna::iRNA_pred::Comparison::Comparaison::sRNA_out
Definition at line 20 of file Comparison.py.
Referenced by createCouple(), createRNAcofoldCouple(), getComparison(), getCouple(), getName(), manageCouple(), runCommand(), and runComparison().
The documentation for this class was generated from the following file:
/home/amine/workspace/iRNA/irna/iRNA_pred/Comparison.py