i-RNA: irna::David2tulip::David::David Class Reference
irna::David2tulip::David::David Class Reference
Public Member Functions
def __init__
Instanciate david object.
def davidConnection
Connection to david.
def analysis
Proceed to DAVID enrichment and store useful data.
def parseChart
Parse DAVID chart data.
def writefile
Pickle DAVID information.
def setdata
Set data from DAVID into the graph.
Public Attributes
listType
david_chart
Detailed Description
Definition at line 14 of file David.py.
Constructor & Destructor Documentation
def irna::David2tulip::David::David::__init__ (self, david_file = None)
Instanciate david object.
Parameters:
david_file,: Path to david file
Definition at line 21 of file David.py.
Member Function Documentation
def irna::David2tulip::David::David::analysis (self, graph)
Proceed to DAVID enrichment and store useful data.
Parameters:
graph,: Graph object
Definition at line 44 of file David.py.
References david_chart, irna::David2tulip::Parser::Parser::getsRNA(), irna::David2tulip::Parser::Parser::getTarget(), listType, parseChart(), and writefile().
Referenced by davidConnection().
def irna::David2tulip::David::David::davidConnection (self)
Connection to david.
Definition at line 32 of file David.py.
References analysis(), and davidConnection().
Referenced by davidConnection().
def irna::David2tulip::David::David::parseChart (self, david_chart, sRNA)
Parse DAVID chart data.
Parameters:
david_chart,: DAVID result
sRNA,: sRNA
Definition at line 68 of file David.py.
References david_chart, irna::David2tulip::Parser::Parser::printObject(), and setdata().
Referenced by analysis().
def irna::David2tulip::David::David::setdata (self, node_objects, edge_objects)
Set data from DAVID into the graph.
Parameters:
node_objects,: List of node objects
edge_objects,: List of edge objects
Returns:
: Node and edge objects
Definition at line 86 of file David.py.
Referenced by parseChart().
def irna::David2tulip::David::David::writefile (self, results)
Pickle DAVID information.
Parameters:
results,: Path to result file
Definition at line 76 of file David.py.
References david_chart, and irna::David2tulip::Parser::Parser::getlinkedge().
Referenced by analysis().
Member Data Documentation
irna::David2tulip::David::David::david_chart
Definition at line 21 of file David.py.
Referenced by analysis(), parseChart(), and writefile().
irna::David2tulip::David::David::listType
Definition at line 21 of file David.py.
Referenced by analysis().
The documentation for this class was generated from the following file:
/home/amine/workspace/iRNA/irna/David2tulip/David.py