i-RNA: irna::David2tulip::Graph::Graph Class Reference
irna::David2tulip::Graph::Graph Class Reference
: Handle Graph
Public Member Functions
def __init__
Instanciate graph object.
def parse
Parse and information to node and edge objects.
def printnodes
Write nodes csv.
def getCategories
Get active categories.
def getNumCategory
Get the position of on element in a list.
def verif
Verif value for sRNA_100.
def filterTermName
Detect the method to use for filtering.
def printedges
Write edges csv.
def writefile
Write node and edge csv.
Public Attributes
node_objects
edge_objects
fcategoryid
gocategoryid
fregex
goregex
Detailed Description
: Handle Graph
Definition at line 16 of file Graph.py.
Constructor & Destructor Documentation
def irna::David2tulip::Graph::Graph::__init__ (self)
Instanciate graph object.
Definition at line 21 of file Graph.py.
Member Function Documentation
def irna::David2tulip::Graph::Graph::filterTermName (self, category, term)
Detect the method to use for filtering.
Definition at line 92 of file Graph.py.
References getCategories(), and printedges().
Referenced by getNumCategory(), and printedges().
def irna::David2tulip::Graph::Graph::getCategories (self)
Get active categories.
Returns:
: Unique categories
Definition at line 61 of file Graph.py.
References getNumCategory(), and verif().
Referenced by filterTermName(), and printnodes().
def irna::David2tulip::Graph::Graph::getNumCategory (self, element, liste)
Get the position of on element in a list.
Parameters:
element,: an element of the list
liste,: a list
Definition at line 74 of file Graph.py.
References edge_objects, and filterTermName().
Referenced by getCategories().
def irna::David2tulip::Graph::Graph::parse (self, obj)
Parse and information to node and edge objects.
Parameters:
obj,: Parser-linked object
Definition at line 34 of file Graph.py.
def irna::David2tulip::Graph::Graph::printedges (self, results)
Write edges csv.
Parameters:
results,: Path to result repertory
Definition at line 111 of file Graph.py.
References edge_objects, filterTermName(), printedges(), printnodes(), and writefile().
Referenced by filterTermName(), and printedges().
def irna::David2tulip::Graph::Graph::printnodes (self, results)
Write nodes csv.
Parameters:
results,: Path to result repertory
Definition at line 42 of file Graph.py.
References edge_objects, getCategories(), and node_objects.
Referenced by printedges().
def irna::David2tulip::Graph::Graph::verif (self)
Verif value for sRNA_100.
Definition at line 81 of file Graph.py.
References fcategoryid, and gocategoryid.
Referenced by getCategories().
def irna::David2tulip::Graph::Graph::writefile (self, results)
Write node and edge csv.
Parameters:
results,: Path to result repertory
Definition at line 174 of file Graph.py.
Referenced by printedges().
Member Data Documentation
irna::David2tulip::Graph::Graph::edge_objects
Definition at line 21 of file Graph.py.
Referenced by getNumCategory(), printedges(), and printnodes().
irna::David2tulip::Graph::Graph::fcategoryid
Definition at line 21 of file Graph.py.
Referenced by verif().
irna::David2tulip::Graph::Graph::fregex
Definition at line 21 of file Graph.py.
irna::David2tulip::Graph::Graph::gocategoryid
Definition at line 21 of file Graph.py.
Referenced by verif().
irna::David2tulip::Graph::Graph::goregex
Definition at line 21 of file Graph.py.
irna::David2tulip::Graph::Graph::node_objects
Definition at line 21 of file Graph.py.
Referenced by printnodes().
The documentation for this class was generated from the following file:
/home/amine/workspace/iRNA/irna/David2tulip/Graph.py