i-RNA: irna::iRNA_stat::Analysis::Analysis Class Reference
irna::iRNA_stat::Analysis::Analysis Class Reference
Public Member Functions
def __init__
Instanciate Analysis object.
def commun_values
Detect commune nan values.
def getRangePosit
Get one column.
Detailed Description
Definition at line 9 of file Analysis.py.
Constructor & Destructor Documentation
def irna::iRNA_stat::Analysis::Analysis::__init__ (self)
Instanciate Analysis object.
Definition at line 14 of file Analysis.py.
Member Function Documentation
def irna::iRNA_stat::Analysis::Analysis::commun_values (self, cumneg_nanvalues, normscore_nanvalues)
Detect commune nan values.
Definition at line 21 of file Analysis.py.
References getRangePosit().
Referenced by irna::iRNA_stat::Regression::Regression::linear_regression(), and irna::iRNA_stat::Draw_data::draw_data::plot_linear_regression().
def irna::iRNA_stat::Analysis::Analysis::getRangePosit (self, array, col)
Get one column.
Parameters:
array,: Matrix array of data
col,: Selected column
Definition at line 33 of file Analysis.py.
Referenced by commun_values(), irna::iRNA_stat::Interaction::Interaction::Interaction_data(), and irna::iRNA_stat::Draw_data::draw_data::write_interaction().
The documentation for this class was generated from the following file:
/home/amine/workspace/iRNA/irna/iRNA_stat/Analysis.py