i-RNA: irna::iRNA_stat::Draw_data::draw_data Class Reference
irna::iRNA_stat::Draw_data::draw_data Class Reference
Public Member Functions
def __init__
Instanciate draw_data object.
def write_curve_param_data
def plot_linear_regression
Plot linear regression of random data.
def getnames
name of sofwares
def plot_roc_curves
Plot roc curve.
def plot_roc_curves_statistics
Statistical analysis of roc.
def write_pValue
Print pValue.
def write_rocthresValue
def write_rocAuc
write AUC
def meanArray
Mean array.
def getPredplotvect
Get float vector from listobj.
def pred_plot
Plot sensitivity and ppv mean.
def write_pred_plot
Write mean sensitivity and ppv of each software.
def write_sens_ppv
Write sensitivity and ppv.
def exec_plot
Plot execution time.
def write_pValueSelect
def write_frequency
def write_similarity
def frequency_plot
def similarity_plot
def write_pValueInteract
def getBoolselect
def write_interaction
def write_general_data
def plot
Plot main function.
Public Attributes
result
Detailed Description
Definition at line 22 of file Draw_data.py.
Constructor & Destructor Documentation
def irna::iRNA_stat::Draw_data::draw_data::__init__ (self, result)
Instanciate draw_data object.
Definition at line 28 of file Draw_data.py.
Member Function Documentation
def irna::iRNA_stat::Draw_data::draw_data::exec_plot (self, execution_time)
Plot execution time.
Parameters:
execution_time,: Execution time
Definition at line 362 of file Draw_data.py.
References result, and write_frequency().
Referenced by plot(), and write_sens_ppv().
def irna::iRNA_stat::Draw_data::draw_data::frequency_plot (self, listobj)
Parameters:
listobj,: List of Computer object
Definition at line 419 of file Draw_data.py.
References result.
Referenced by plot(), and write_frequency().
def irna::iRNA_stat::Draw_data::draw_data::getBoolselect (self, obj, i)
Definition at line 459 of file Draw_data.py.
References result, and write_general_data().
Referenced by similarity_plot(), and write_pValueInteract().
def irna::iRNA_stat::Draw_data::draw_data::getnames (self, listobj)
name of sofwares
Parameters:
listobj,: List of Computer object
Definition at line 151 of file Draw_data.py.
References plot_roc_curves(), and result.
Referenced by getPredplotvect(), plot_linear_regression(), and plot_roc_curves().
def irna::iRNA_stat::Draw_data::draw_data::getPredplotvect (self, listobj)
Get float vector from listobj.
Parameters:
listobj,: List of Computer object
Definition at line 296 of file Draw_data.py.
References getnames(), result, and write_pred_plot().
Referenced by meanArray(), and write_rocAuc().
def irna::iRNA_stat::Draw_data::draw_data::meanArray (self, array)
Mean array.
Parameters:
array,: Matrix array
Definition at line 282 of file Draw_data.py.
References getPredplotvect(), meanArray(), and pred_plot().
Referenced by meanArray(), pred_plot(), and write_rocAuc().
def irna::iRNA_stat::Draw_data::draw_data::plot (self, args, soft_inf, listobj, dbmanage, execution_time)
Plot main function.
Definition at line 504 of file Draw_data.py.
References exec_plot(), frequency_plot(), pred_plot(), similarity_plot(), write_frequency(), write_pred_plot(), write_pValueSelect(), write_sens_ppv(), and write_similarity().
Referenced by write_interaction().
def irna::iRNA_stat::Draw_data::draw_data::plot_linear_regression (self, obj, soft_inf, numsoft, dbmanage)
Plot linear regression of random data.
Parameters:
obj,: Computer object
soft_inf,: Software information
numsoft,: Number of the soft
dbmanage,: Access to the database
Definition at line 109 of file Draw_data.py.
References irna::iRNA_stat::Analysis::Analysis::commun_values(), getnames(), and result.
Referenced by write_curve_param_data(), and write_interaction().
def irna::iRNA_stat::Draw_data::draw_data::plot_roc_curves (self, listobj)
Plot roc curve.
Parameters:
listobj,: List of Computer object
Definition at line 162 of file Draw_data.py.
References getnames(), plot_roc_curves_statistics(), and result.
Referenced by getnames(), and write_general_data().
def irna::iRNA_stat::Draw_data::draw_data::plot_roc_curves_statistics (self, listobj)
Statistical analysis of roc.
Parameters:
listobj,: List of Computer object
Definition at line 203 of file Draw_data.py.
References result, and write_pValue().
Referenced by plot_roc_curves(), and write_general_data().
def irna::iRNA_stat::Draw_data::draw_data::pred_plot (self, listobj)
Plot sensitivity and ppv mean.
Parameters:
listobj,: List of Computer object
Definition at line 307 of file Draw_data.py.
References meanArray(), result, and write_sens_ppv().
Referenced by meanArray(), and plot().
def irna::iRNA_stat::Draw_data::draw_data::similarity_plot (self, listobj)
Parameters:
listobj,: List of Computer object
Definition at line 430 of file Draw_data.py.
References getBoolselect(), and write_interaction().
Referenced by plot(), and write_similarity().
def irna::iRNA_stat::Draw_data::draw_data::write_curve_param_data (self, listobj, dbmanage)
Parameters:
listobj,: List of Computer object
dbmanage,: Access to the database
Definition at line 37 of file Draw_data.py.
References plot_linear_regression().
Referenced by write_interaction().
def irna::iRNA_stat::Draw_data::draw_data::write_frequency (self, listobj)
Parameters:
listobj,: List of Computer object
Definition at line 387 of file Draw_data.py.
References frequency_plot(), and result.
Referenced by exec_plot(), and plot().
def irna::iRNA_stat::Draw_data::draw_data::write_general_data (self, listobj)
Parameters:
listobj,: List of Computer object
Definition at line 488 of file Draw_data.py.
References plot_roc_curves(), plot_roc_curves_statistics(), write_general_data(), write_interaction(), write_pValue(), write_pValueInteract(), write_rocAuc(), and write_rocthresValue().
Referenced by getBoolselect(), and write_general_data().
def irna::iRNA_stat::Draw_data::draw_data::write_interaction (self, listobj, dbmanage, selection)
Definition at line 466 of file Draw_data.py.
References irna::iRNA_stat::Analysis::Analysis::getRangePosit(), plot(), plot_linear_regression(), and write_curve_param_data().
Referenced by similarity_plot(), and write_general_data().
def irna::iRNA_stat::Draw_data::draw_data::write_pred_plot (self, listobj)
Write mean sensitivity and ppv of each software.
Parameters:
listobj,: List of Computer object
dbmanage,: Access to the database
Definition at line 325 of file Draw_data.py.
References result.
Referenced by getPredplotvect(), and plot().
def irna::iRNA_stat::Draw_data::draw_data::write_pValue (self, listobj, dbmanage)
Print pValue.
Parameters:
listobj,: List of Computer object
dbmanage,: Access to the database
Definition at line 225 of file Draw_data.py.
References result, and write_rocthresValue().
Referenced by plot_roc_curves_statistics(), and write_general_data().
def irna::iRNA_stat::Draw_data::draw_data::write_pValueInteract (self, listobj, dbmanage)
Parameters:
listobj,: List of Computer object
dbmanage,: Access to the database
Definition at line 442 of file Draw_data.py.
References getBoolselect(), and result.
Referenced by write_general_data(), and write_similarity().
def irna::iRNA_stat::Draw_data::draw_data::write_pValueSelect (self, listobj)
Parameters:
listobj,: List of Computer object
Definition at line 372 of file Draw_data.py.
References result, and write_similarity().
Referenced by plot(), and write_sens_ppv().
def irna::iRNA_stat::Draw_data::draw_data::write_rocAuc (self, listobj, auc_result)
write AUC
Parameters:
listobj,: List of Computer object
auc_result,: AUC result
Definition at line 264 of file Draw_data.py.
References getPredplotvect(), and meanArray().
Referenced by write_general_data(), and write_rocthresValue().
def irna::iRNA_stat::Draw_data::draw_data::write_rocthresValue (self, listobj, coords_roc, dbmanage)
Parameters:
listobj,: List of Computer object
coords_roc,: Roc coordinates
dbmanage,: Access to the database
Definition at line 245 of file Draw_data.py.
References result, and write_rocAuc().
Referenced by write_general_data(), and write_pValue().
def irna::iRNA_stat::Draw_data::draw_data::write_sens_ppv (self, listobj, dbmanage)
Write sensitivity and ppv.
Parameters:
listobj,: List of Computer object
dbmanage,: Access to the database
Definition at line 342 of file Draw_data.py.
References exec_plot(), result, and write_pValueSelect().
Referenced by plot(), and pred_plot().
def irna::iRNA_stat::Draw_data::draw_data::write_similarity (self, listobj)
Parameters:
listobj,: List of Computer object
Definition at line 403 of file Draw_data.py.
References result, similarity_plot(), and write_pValueInteract().
Referenced by plot(), and write_pValueSelect().
Member Data Documentation
irna::iRNA_stat::Draw_data::draw_data::result
Definition at line 28 of file Draw_data.py.
Referenced by exec_plot(), frequency_plot(), getBoolselect(), getnames(), getPredplotvect(), plot_linear_regression(), plot_roc_curves(), plot_roc_curves_statistics(), pred_plot(), write_frequency(), write_pred_plot(), write_pValue(), write_pValueInteract(), write_pValueSelect(), write_rocthresValue(), write_sens_ppv(), and write_similarity().
The documentation for this class was generated from the following file:
/home/amine/workspace/iRNA/irna/iRNA_stat/Draw_data.py