i-RNA: irna::iRNA_pred::Fasta::Fasta Class Reference
irna::iRNA_pred::Fasta::Fasta Class Reference
: Write fasta needed for the different software from a multifasta
Public Member Functions
def __init__
Build fasta object.
def WriteFasta
Write the fasta.
def EmptyRep
Empty the folder of fasta files.
def ExtractFasta
Public Attributes
cacheFasta
fastafile
Static Public Attributes
tuple regex = re.compile("^>(\S+)\s*\S*")
tuple regex_seq = re.compile("^[ATGCatgc]+\S*")
tuple multifasta = open(mf, "r")
cacheData = False
tuple a = regex.match(i)
tuple seqname = a.group(1)
Detailed Description
: Write fasta needed for the different software from a multifasta
Definition at line 15 of file Fasta.py.
Constructor & Destructor Documentation
def irna::iRNA_pred::Fasta::Fasta::__init__ (self)
Build fasta object.
Reimplemented from irna::iRNA_pred::Stat::Stat.
Definition at line 21 of file Fasta.py.
Member Function Documentation
def irna::iRNA_pred::Fasta::Fasta::EmptyRep (self, fasta_out)
Empty the folder of fasta files.
Parameters:
fasta_out,: Fasta repertory
Definition at line 49 of file Fasta.py.
References ExtractFasta().
Referenced by ExtractFasta(), and WriteFasta().
def irna::iRNA_pred::Fasta::Fasta::ExtractFasta (self, mf, fasta_out)
Definition at line 64 of file Fasta.py.
References EmptyRep(), irna::iRNA_pred::RanRNA::RanRNA::GC, irna::iRNA_pred::RanRNA::RanRNA::NbSeq, and irna::iRNA_pred::Stat::Stat::openSeqInf().
Referenced by EmptyRep().
def irna::iRNA_pred::Fasta::Fasta::WriteFasta (self)
Write the fasta.
Definition at line 33 of file Fasta.py.
References cacheFasta, EmptyRep(), and fastafile.
Referenced by irna::iRNA_pred::RanRNA::RanRNA::WriteFasta().
Member Data Documentation
tuple irna::iRNA_pred::Fasta::Fasta::a = regex.match(i) [static]
Definition at line 89 of file Fasta.py.
irna::iRNA_pred::Fasta::Fasta::cacheData = False [static]
Definition at line 87 of file Fasta.py.
irna::iRNA_pred::Fasta::Fasta::cacheFasta
Definition at line 21 of file Fasta.py.
Referenced by WriteFasta().
irna::iRNA_pred::Fasta::Fasta::fastafile
Definition at line 21 of file Fasta.py.
Referenced by WriteFasta(), and irna::iRNA_pred::RanRNA::RanRNA::WriteFasta().
tuple irna::iRNA_pred::Fasta::Fasta::multifasta = open(mf, "r") [static]
Definition at line 85 of file Fasta.py.
tuple irna::iRNA_pred::Fasta::Fasta::regex = re.compile("^>(\S+)\s*\S*") [static]
Extract multifasta to fasta.
@param mf: Multifasta file
@param fasta_out: Fasta repertory
Definition at line 81 of file Fasta.py.
tuple irna::iRNA_pred::Fasta::Fasta::regex_seq = re.compile("^[ATGCatgc]+\S*") [static]
Definition at line 82 of file Fasta.py.
tuple irna::iRNA_pred::Fasta::Fasta::seqname = a.group(1) [static]
Definition at line 91 of file Fasta.py.
The documentation for this class was generated from the following file:
/home/amine/workspace/iRNA/irna/iRNA_pred/Fasta.py