i-RNA: irna::iRNA_pred::iRNA_pred Namespace Reference
irna::iRNA_pred::iRNA_pred Namespace Reference
Functions
def WriteAllExecTime
Write execution time.
def saveData
Save data in a sqlite database.
def main
: Main program
Function Documentation
def irna::iRNA_pred::iRNA_pred::main ()
: Main program
Author:
: Amine Ghozlane
Definition at line 68 of file iRNA_pred.py.
References saveData(), and WriteAllExecTime().
Referenced by saveData().
def irna::iRNA_pred::iRNA_pred::saveData (data_files, fastmode)
Save data in a sqlite database.
Definition at line 40 of file iRNA_pred.py.
References main().
Referenced by main(), and WriteAllExecTime().
def irna::iRNA_pred::iRNA_pred::WriteAllExecTime (result_out, start, end)
Write execution time.
Parameters:
result_out,: Time result
start,: Date of start
end,: Date of end
Definition at line 25 of file iRNA_pred.py.
References saveData().
Referenced by main().